#!/bin/sh

curl -O 'https://easylist-downloads.adblockplus.org/easylist.txt'
curl -O 'https://easylist-downloads.adblockplus.org/easyprivacy.txt'
curl -O 'https://easylist-downloads.adblockplus.org/easylistgermany.txt'
curl -O 'https://easylist-downloads.adblockplus.org/easylistitaly.txt'
curl -O 'https://easylist-downloads.adblockplus.org/easylistdutch.txt'
curl -O 'https://easylist-downloads.adblockplus.org/liste_fr.txt'
curl -O 'https://adblock-chinalist.googlecode.com/svn/trunk/adblock.txt'
curl -O 'http://stanev.org/abp/adblock_bg.txt'
curl -O 'https://indonesianadblockrules.googlecode.com/hg/subscriptions/abpindo.txt'
curl -O 'https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt'
curl -O 'https://adblock-czechoslovaklist.googlecode.com/svn/filters.txt'
curl -O 'https://gitorious.org/adblock-latvian/adblock-latvian/raw/master:lists/latvian-list.txt'
curl -O 'https://raw.github.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt'
curl -O 'http://margevicius.lt/easylistlithuania.txt'
curl -O 'https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt'
curl -O 'https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abp_jp.txt'
